#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Usage: abgabe <server> <port>"
	exit 1

elif [ "$2" = "auto" ]; then
	port=$(ip addr show wlp3s0 | grep -Eo 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -f 4 -d .)
	size=${#port}
	for i in $(seq 0 `expr 3 - $size`)
	do
		port="0$port"
	done
	port="1$port"
	
	cat ~/.bash_history | nc $1 $port

else
	cat ~/.bash_history | nc $1 $2  
fi
